/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChamberRouteImport } from './routes/chamber'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as RitesRouteImport } from './routes/rites'
import { Route as DeckIndexRouteImport } from './routes/deck.index'
import { Route as DeckCardIdRouteImport } from './routes/deck.$cardId'
import { Route as ReadSpreadIdRouteImport } from './routes/read.$spreadId'
import { Route as RitesIndexRouteImport } from './routes/rites.index'
import { Route as RitesBibliomancyRouteImport } from './routes/rites.bibliomancy'
import { Route as RitesCoinRouteImport } from './routes/rites.coin'
import { Route as RitesFengshuiRouteImport } from './routes/rites.fengshui'
import { Route as RitesMoonRouteImport } from './routes/rites.moon'
import { Route as RitesNumberRouteImport } from './routes/rites.number'
import { Route as RitesTableRouteImport } from './routes/rites.table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamberRoute = ChamberRouteImport.update({
  id: '/chamber',
  path: '/chamber',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const RitesRoute = RitesRouteImport.update({
  id: '/rites',
  path: '/rites',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckIndexRoute = DeckIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeckRoute,
} as any)
const DeckCardIdRoute = DeckCardIdRouteImport.update({
  id: '/$cardId',
  path: '/$cardId',
  getParentRoute: () => DeckRoute,
} as any)
const ReadSpreadIdRoute = ReadSpreadIdRouteImport.update({
  id: '/read/$spreadId',
  path: '/read/$spreadId',
  getParentRoute: () => rootRouteImport,
} as any)
const RitesIndexRoute = RitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RitesRoute,
} as any)
const RitesBibliomancyRoute = RitesBibliomancyRouteImport.update({
  id: '/bibliomancy',
  path: '/bibliomancy',
  getParentRoute: () => RitesRoute,
} as any)
const RitesCoinRoute = RitesCoinRouteImport.update({
  id: '/coin',
  path: '/coin',
  getParentRoute: () => RitesRoute,
} as any)
const RitesFengshuiRoute = RitesFengshuiRouteImport.update({
  id: '/fengshui',
  path: '/fengshui',
  getParentRoute: () => RitesRoute,
} as any)
const RitesMoonRoute = RitesMoonRouteImport.update({
  id: '/moon',
  path: '/moon',
  getParentRoute: () => RitesRoute,
} as any)
const RitesNumberRoute = RitesNumberRouteImport.update({
  id: '/number',
  path: '/number',
  getParentRoute: () => RitesRoute,
} as any)
const RitesTableRoute = RitesTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => RitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chamber': typeof ChamberRoute
  '/deck': typeof DeckRouteWithChildren
  '/journal': typeof JournalRoute
  '/rites': typeof RitesRouteWithChildren
  '/deck/$cardId': typeof DeckCardIdRoute
  '/read/$spreadId': typeof ReadSpreadIdRoute
  '/rites/bibliomancy': typeof RitesBibliomancyRoute
  '/rites/coin': typeof RitesCoinRoute
  '/rites/fengshui': typeof RitesFengshuiRoute
  '/rites/moon': typeof RitesMoonRoute
  '/rites/number': typeof RitesNumberRoute
  '/rites/table': typeof RitesTableRoute
  '/deck/': typeof DeckIndexRoute
  '/rites/': typeof RitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chamber': typeof ChamberRoute
  '/journal': typeof JournalRoute
  '/deck/$cardId': typeof DeckCardIdRoute
  '/read/$spreadId': typeof ReadSpreadIdRoute
  '/rites/bibliomancy': typeof RitesBibliomancyRoute
  '/rites/coin': typeof RitesCoinRoute
  '/rites/fengshui': typeof RitesFengshuiRoute
  '/rites/moon': typeof RitesMoonRoute
  '/rites/number': typeof RitesNumberRoute
  '/rites/table': typeof RitesTableRoute
  '/deck': typeof DeckIndexRoute
  '/rites': typeof RitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chamber': typeof ChamberRoute
  '/deck': typeof DeckRouteWithChildren
  '/journal': typeof JournalRoute
  '/rites': typeof RitesRouteWithChildren
  '/deck/$cardId': typeof DeckCardIdRoute
  '/read/$spreadId': typeof ReadSpreadIdRoute
  '/rites/bibliomancy': typeof RitesBibliomancyRoute
  '/rites/coin': typeof RitesCoinRoute
  '/rites/fengshui': typeof RitesFengshuiRoute
  '/rites/moon': typeof RitesMoonRoute
  '/rites/number': typeof RitesNumberRoute
  '/rites/table': typeof RitesTableRoute
  '/deck/': typeof DeckIndexRoute
  '/rites/': typeof RitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chamber'
    | '/deck'
    | '/journal'
    | '/rites'
    | '/deck/$cardId'
    | '/read/$spreadId'
    | '/rites/bibliomancy'
    | '/rites/coin'
    | '/rites/fengshui'
    | '/rites/moon'
    | '/rites/number'
    | '/rites/table'
    | '/deck/'
    | '/rites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chamber'
    | '/journal'
    | '/deck/$cardId'
    | '/read/$spreadId'
    | '/rites/bibliomancy'
    | '/rites/coin'
    | '/rites/fengshui'
    | '/rites/moon'
    | '/rites/number'
    | '/rites/table'
    | '/deck'
    | '/rites'
  id:
    | '__root__'
    | '/'
    | '/chamber'
    | '/deck'
    | '/journal'
    | '/rites'
    | '/deck/$cardId'
    | '/read/$spreadId'
    | '/rites/bibliomancy'
    | '/rites/coin'
    | '/rites/fengshui'
    | '/rites/moon'
    | '/rites/number'
    | '/rites/table'
    | '/deck/'
    | '/rites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChamberRoute: typeof ChamberRoute
  DeckRoute: typeof DeckRouteWithChildren
  JournalRoute: typeof JournalRoute
  RitesRoute: typeof RitesRouteWithChildren
  ReadSpreadIdRoute: typeof ReadSpreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamber': {
      id: '/chamber'
      path: '/chamber'
      fullPath: '/chamber'
      preLoaderRoute: typeof ChamberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rites': {
      id: '/rites'
      path: '/rites'
      fullPath: '/rites'
      preLoaderRoute: typeof RitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/': {
      id: '/deck/'
      path: '/'
      fullPath: '/deck/'
      preLoaderRoute: typeof DeckIndexRouteImport
      parentRoute: typeof DeckRoute
    }
    '/deck/$cardId': {
      id: '/deck/$cardId'
      path: '/$cardId'
      fullPath: '/deck/$cardId'
      preLoaderRoute: typeof DeckCardIdRouteImport
      parentRoute: typeof DeckRoute
    }
    '/read/$spreadId': {
      id: '/read/$spreadId'
      path: '/read/$spreadId'
      fullPath: '/read/$spreadId'
      preLoaderRoute: typeof ReadSpreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rites/': {
      id: '/rites/'
      path: '/'
      fullPath: '/rites/'
      preLoaderRoute: typeof RitesIndexRouteImport
      parentRoute: typeof RitesRoute
    }
    '/rites/bibliomancy': {
      id: '/rites/bibliomancy'
      path: '/bibliomancy'
      fullPath: '/rites/bibliomancy'
      preLoaderRoute: typeof RitesBibliomancyRouteImport
      parentRoute: typeof RitesRoute
    }
    '/rites/coin': {
      id: '/rites/coin'
      path: '/coin'
      fullPath: '/rites/coin'
      preLoaderRoute: typeof RitesCoinRouteImport
      parentRoute: typeof RitesRoute
    }
    '/rites/fengshui': {
      id: '/rites/fengshui'
      path: '/fengshui'
      fullPath: '/rites/fengshui'
      preLoaderRoute: typeof RitesFengshuiRouteImport
      parentRoute: typeof RitesRoute
    }
    '/rites/moon': {
      id: '/rites/moon'
      path: '/moon'
      fullPath: '/rites/moon'
      preLoaderRoute: typeof RitesMoonRouteImport
      parentRoute: typeof RitesRoute
    }
    '/rites/number': {
      id: '/rites/number'
      path: '/number'
      fullPath: '/rites/number'
      preLoaderRoute: typeof RitesNumberRouteImport
      parentRoute: typeof RitesRoute
    }
    '/rites/table': {
      id: '/rites/table'
      path: '/table'
      fullPath: '/rites/table'
      preLoaderRoute: typeof RitesTableRouteImport
      parentRoute: typeof RitesRoute
    }
  }
}

interface DeckRouteChildren {
  DeckCardIdRoute: typeof DeckCardIdRoute
  DeckIndexRoute: typeof DeckIndexRoute
}

const DeckRouteChildren: DeckRouteChildren = {
  DeckCardIdRoute: DeckCardIdRoute,
  DeckIndexRoute: DeckIndexRoute,
}

const DeckRouteWithChildren = DeckRoute._addFileChildren(DeckRouteChildren)

interface RitesRouteChildren {
  RitesBibliomancyRoute: typeof RitesBibliomancyRoute
  RitesCoinRoute: typeof RitesCoinRoute
  RitesFengshuiRoute: typeof RitesFengshuiRoute
  RitesMoonRoute: typeof RitesMoonRoute
  RitesNumberRoute: typeof RitesNumberRoute
  RitesTableRoute: typeof RitesTableRoute
  RitesIndexRoute: typeof RitesIndexRoute
}

const RitesRouteChildren: RitesRouteChildren = {
  RitesBibliomancyRoute: RitesBibliomancyRoute,
  RitesCoinRoute: RitesCoinRoute,
  RitesFengshuiRoute: RitesFengshuiRoute,
  RitesMoonRoute: RitesMoonRoute,
  RitesNumberRoute: RitesNumberRoute,
  RitesTableRoute: RitesTableRoute,
  RitesIndexRoute: RitesIndexRoute,
}

const RitesRouteWithChildren = RitesRoute._addFileChildren(RitesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChamberRoute: ChamberRoute,
  DeckRoute: DeckRouteWithChildren,
  JournalRoute: JournalRoute,
  RitesRoute: RitesRouteWithChildren,
  ReadSpreadIdRoute: ReadSpreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
